name: synthetic-data-generator
description: "Streamlit app to configure and generate synthetic data written to Unity Catalog"


command: 
  - streamlit
  - run
  - app.py
  - --server.address=0.0.0.0
  - --server.port=8000
  - --server.headless=true
  - --server.enableCORS=false
  - --server.enableXsrfProtection=false

resources:
  memory: "2Gi"      # Increase memory
  cpu: "1000m"       # Increase CPU

env:
  - name: PYTHONPATH
    value: /app:/app/python/source_code
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"